const UPDATE_NAV = 'UPDATE_NAV';
const UPDATE_SELECTED = 'UPDATE_SELECTED';
const UPDATE_DRAFT = 'UPDATE_DRAFT';
const DRAFT_GOLFER = 'UPDATE_PLAYER_GOLFERS';
const SET_DRAFT_BOARD = 'SET_DRAFT_BOARD';

module.exports = {
  UPDATE_NAV,
  UPDATE_SELECTED,
  UPDATE_DRAFT,
  DRAFT_GOLFER,
  SET_DRAFT_BOARD
};
