const UPDATE_NAV = 'UPDATE_NAV';
const UPDATE_SELECTED = 'UPDATE_SELECTED';
const UPDATE_DRAFT = 'UPDATE_DRAFT';
const DRAFT_GOLFER = 'UPDATE_PLAYER_GOLFERS';

module.exports = {
  UPDATE_NAV,
  UPDATE_SELECTED,
  UPDATE_DRAFT,
  DRAFT_GOLFER,
};
